# Generated by Django 4.2.7 on 2023-12-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_link', models.URLField(default='example.com')),
                ('version_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='cited_by_link',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='paper',
            name='cited_by_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='related_articles_link',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='paper',
            name='version_link',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='paper',
            name='version_number',
            field=models.IntegerField(default=0),
        ),
    ]
