# Generated by Django 4.2.7 on 2023-11-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scrapeddata_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='content',
        ),
    ]
