# Generated by Django 4.2.7 on 2023-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_version_paper_cited_by_link_paper_cited_by_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('year', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=300)),
                ('publication', models.CharField(default='', max_length=300)),
                ('field', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
