# Generated by Django 4.2.7 on 2023-12-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PaperCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_by_link', models.URLField(default='http://example.com')),
                ('cited_by_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_link', models.URLField(default='http://example.com')),
                ('version_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('link', models.URLField(default='http://example.com')),
                ('related_patents', models.URLField(default='http://example.com')),
                ('year', models.IntegerField(default=0)),
                ('patent_host', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PatentCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_by_link', models.URLField(default='http://example.com')),
                ('cited_by_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_link', models.URLField(default='http://example.com')),
                ('version_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
        migrations.DeleteModel(
            name='ScrapingStatus',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='cited_by_link',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='cited_by_number',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='version_link',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='version_number',
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
