# Generated by Django 4.2.7 on 2023-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_scrapeddata_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(default='http://example.com')),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
