# Generated by Django 4.2.7 on 2023-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_citation_alter_paper_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
