# Generated by Django 4.2.7 on 2023-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_numberofresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='NumberOfResults',
        ),
    ]
