# Generated by Django 4.2.7 on 2023-12-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_relevcance_paper_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cited_by_number',
            field=models.IntegerField(default=0),
        ),
    ]
