# Generated by Django 4.2.7 on 2023-12-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_paper_cited_by_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cited_by_link',
            field=models.URLField(default='http://example.com'),
        ),
    ]
