# Generated by Django 4.2.7 on 2023-12-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_author_company_fieldofstudy_inventor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='JournalConference',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='InventorID',
        ),
        migrations.RemoveField(
            model_name='patentfieldofstudy',
            name='FieldOfStudyID',
        ),
        migrations.RemoveField(
            model_name='patentfieldofstudy',
            name='PatentID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CompanyID',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='FieldOfStudy',
        ),
        migrations.DeleteModel(
            name='Inventor',
        ),
        migrations.DeleteModel(
            name='Patent',
        ),
        migrations.DeleteModel(
            name='PatentFieldOfStudy',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
